Vagrant.configure(2) do |config|
  # config.vm.box = "bento/centos-6.7"
  config.vm.box = "bento/ubuntu-15.04"
  # config.vbguest.auto_update = false

   config.vm.define :svr01 do |server|
     ### determined specific IP.
     server.vm.network "private_network", ip: "192.168.33.71"
     ### vbox name
     server.vm.hostname = 'db01'
   end
  # config.vm.define :svr02 do |server|
  #   ### determined specific IP.
  #   server.vm.network "private_network", ip: "192.168.33.72"
  #   ### vbox name
  #   server.vm.hostname = 'db02'
  # end

  config.vm.provider "virtualbox" do |vb|
    ### vagrant hostname 
    # vb.name = "try-db-mysql"
    vb.customize ['modifyvm', :id,"--memory", 512]
    vb.customize ['modifyvm', :id,"--natdnshostresolver1", "on"]
    vb.customize ['modifyvm', :id,"--natdnsproxy1", "on"]
  end  
 
  ### settitng of synced_folder
  config.vm.synced_folder "../", "/srv/try-db-mysql", \
    :create => true, \
    :owner  => 'root', \
    :group  => 'root', \
    :mount_options => ['dmode=777,fmode=755'] 

  config.vm.provision :shell, :path => "ssh/init.sh"

  ### config.vm.provision "ansible" do |ansible|
  ###   ansible.playbook = "playbook/site.yml"
  ###   ansible.inventory_path = "playbook/staging"
  ###   ansible.limit = 'all'
  ### end

end
